"""Typed event dataclasses for the openHarness stream.

Mirror the NDJSON shapes emitted by `oh run --output-format stream-json`
(``src/main.tsx`` stream-json branch). Keeping these in lockstep with the
CLI's output is essential — any divergence breaks streaming.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Any

__all__ = [
    "CostUpdate",
    "ErrorEvent",
    "Event",
    "HookDecision",
    "TextDelta",
    "ToolEnd",
    "ToolStart",
    "TurnComplete",
    "TurnStart",
    "TurnStop",
    "UnknownEvent",
    "parse_event",
]


@dataclass(frozen=True)
class Event:
    """Base class for all streamed events. Do not instantiate directly."""


@dataclass(frozen=True)
class TextDelta(Event):
    """A chunk of text generated by the assistant."""

    content: str


@dataclass(frozen=True)
class ToolStart(Event):
    """The assistant has begun invoking a tool."""

    tool: str


@dataclass(frozen=True)
class ToolEnd(Event):
    """A tool invocation has completed."""

    tool: str
    output: str
    error: bool


@dataclass(frozen=True)
class ErrorEvent(Event):
    """A recoverable error occurred during the turn."""

    message: str


@dataclass(frozen=True)
class CostUpdate(Event):
    """Cost and token counts updated after a completed request."""

    input_tokens: int
    output_tokens: int
    cost: float
    model: str


@dataclass(frozen=True)
class TurnComplete(Event):
    """A turn has ended. ``reason`` is ``"completed"`` for normal end,
    ``"max_turns"`` when the turn cap was hit, ``"error"`` on failure, etc.

    Emitted by ``query()`` for each subagent turn. For top-level turn
    boundaries, watch :class:`TurnStart` and :class:`TurnStop`.
    """

    reason: str


@dataclass(frozen=True)
class TurnStart(Event):
    """A top-level agent turn has begun.

    New in CLI v2.16.0 / SDK v0.4.0. ``turn_number`` is zero-indexed
    within the current session (one-shot ``query()`` calls always see 0).
    """

    turn_number: int


@dataclass(frozen=True)
class TurnStop(Event):
    """A top-level agent turn has ended.

    New in CLI v2.16.0 / SDK v0.4.0. Mirrors Claude Code's ``Stop`` hook
    event. ``reason`` is ``"completed"``, ``"max_turns"``, ``"error"``,
    or ``"interrupted"``.
    """

    turn_number: int
    reason: str


@dataclass(frozen=True)
class HookDecision(Event):
    """A hook produced a permission decision during this turn.

    New in CLI v2.16.0 / SDK v0.4.0. Fires for any hook (user-configured
    via ``.oh/config.yaml`` or injected by the SDK via ``can_use_tool``)
    that returns an ``allow`` / ``deny`` / ``ask`` decision.
    """

    event: str
    tool: str | None
    decision: str
    reason: str | None


@dataclass(frozen=True)
class UnknownEvent(Event):
    """Fallback for event types the SDK doesn't recognize yet.

    Kept so forward-compatible CLI versions that emit new event types
    don't break existing Python clients — they just observe an
    ``UnknownEvent`` with the raw payload.
    """

    raw: dict[str, Any]


def parse_event(obj: dict[str, Any]) -> Event:
    """Parse one NDJSON object into a typed :class:`Event`.

    Unknown ``type`` values become :class:`UnknownEvent` so forward-compatible
    CLI versions can add new event types without breaking existing clients.

    :param obj: Decoded JSON object (already run through ``json.loads``).
    :returns: A typed Event subclass.
    :raises TypeError: if ``obj`` is not a dict.
    """
    if not isinstance(obj, dict):
        raise TypeError(f"Event payload must be a dict, got {type(obj).__name__}")
    kind = obj.get("type")
    if kind == "text":
        return TextDelta(content=str(obj.get("content", "")))
    if kind == "tool_start":
        return ToolStart(tool=str(obj.get("tool", "")))
    if kind == "tool_end":
        return ToolEnd(
            tool=str(obj.get("tool", "")),
            output=str(obj.get("output", "")),
            error=bool(obj.get("error", False)),
        )
    if kind == "error":
        return ErrorEvent(message=str(obj.get("message", "")))
    if kind == "cost_update":
        return CostUpdate(
            input_tokens=int(obj.get("inputTokens", 0)),
            output_tokens=int(obj.get("outputTokens", 0)),
            cost=float(obj.get("cost", 0.0)),
            model=str(obj.get("model", "")),
        )
    if kind == "turn_complete":
        return TurnComplete(reason=str(obj.get("reason", "completed")))
    if kind == "turnStart":
        return TurnStart(turn_number=int(obj.get("turnNumber", 0)))
    if kind == "turnStop":
        return TurnStop(
            turn_number=int(obj.get("turnNumber", 0)),
            reason=str(obj.get("reason", "completed")),
        )
    if kind == "hook_decision":
        tool_val = obj.get("tool")
        reason_val = obj.get("reason")
        return HookDecision(
            event=str(obj.get("event", "")),
            tool=str(tool_val) if tool_val is not None else None,
            decision=str(obj.get("decision", "")),
            reason=str(reason_val) if reason_val is not None else None,
        )
    return UnknownEvent(raw=dict(obj))
